configform_example.settings:
  type: config_object
  label: 'Configform Example settings'
  mapping:
    email_address:
      type: string
      label: 'This is the example email address.'
    address:
      line_1:
        type: string
        label: 'line 1 name'
      city:
        type: string
        label: 'city name'
      state:
        type: string
        label: 'state name'
      zip:
        type: string
        label: 'zip code'
