<?php

/**
 * @file
 * Contains article_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function article_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the article_content module.
    case 'help.page.article_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Article content (no revisions, no translations).') . '</p>';
      return $output;

    default:
  }
}
